#!/usr/bin/env bash
set -euo pipefail

# ── Conduit Secret Generator ──────────────────────────────────
# Generates secure random values for JWT_SECRET, JWT_REFRESH_SECRET,
# and CONDUIT_HOOK_TOKEN, then writes them to .env in the repo root.
#
# Safe to re-run: skips generation if .env already exists.
# To regenerate, delete .env and re-run this script.

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Dependency check ─────────────────────────────────────────
command -v openssl >/dev/null 2>&1 || error "openssl is required but not installed."

# ── Locate repo root ─────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

# ── Idempotency: skip if .env already exists ─────────────────
if [ -f "$ENV_FILE" ]; then
    warn ".env already exists. Skipping generation."
    echo ""
    echo -e "  To regenerate secrets, delete .env and re-run this script."
    exit 0
fi

# ── Generate secrets ─────────────────────────────────────────
JWT_SECRET="$(openssl rand -base64 48)"
JWT_REFRESH_SECRET="$(openssl rand -base64 48)"
CONDUIT_HOOK_TOKEN="$(openssl rand -hex 32)"

echo ""
echo -e "${BOLD}Generated secrets:${NC}"
echo -e "  ${CYAN}JWT_SECRET${NC}:          $JWT_SECRET"
echo -e "  ${CYAN}JWT_REFRESH_SECRET${NC}:  $JWT_REFRESH_SECRET"
echo -e "  ${CYAN}CONDUIT_HOOK_TOKEN${NC}:  $CONDUIT_HOOK_TOKEN"
echo ""

# ── Write .env ────────────────────────────────────────────────
# Use a temp file + mv for atomic replacement (safe on all POSIX systems).
TMP="$(mktemp)"

cat > "$TMP" <<EOF
# Conduit secrets — generated by generate-secrets.sh
# Do NOT commit this file. It is listed in .gitignore.
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
CONDUIT_HOOK_TOKEN=$CONDUIT_HOOK_TOKEN
EOF

mv "$TMP" "$ENV_FILE"
chmod 600 "$ENV_FILE"

info "Secrets written to .env (mode 600)."
echo ""
echo -e "${YELLOW}Keep .env private — it contains your secrets.${NC}"
echo -e "${YELLOW}It is listed in .gitignore; do not commit it.${NC}"
echo ""
